# 此工作流将对节点依赖项进行全新安装，缓存/恢复这些依赖项，构建源代码，并在不同版本的节点上运行测试
# 更多信息请参阅：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

名称: Node.js CI

触发:
推送:
分支: [ "main" ]
拉取请求:
分支: [ "main" ]

作业:
构建:

运行于:       矩阵
节点版本: [18.x,20.x,22.x]
        # 请访问 https://nodejs.org/en/about/releases/ 查阅支持的Node.js发布计划

:
    - uses: actions/checkout@v4
    - 名称: 使用 Node.js ${{matrix.node-version}}
使用: actions/setup-node@v4
与:
节点版本: ${{matrix.node-version}}
缓存: 'npm'
    - 运行: npm ci
    - 运行: npm run build --if-present
    - 运行: npm test
